// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/emccode/libstorage/client (interfaces: Client)

package storage

import (
	types0 "github.com/emccode/libstorage/api/types"
	types "github.com/emccode/libstorage/drivers/storage/libstorage/types"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *_MockClientRecorder
}

// Recorder for MockClient (not exported)
type _MockClientRecorder struct {
	mock *MockClient
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &_MockClientRecorder{mock}
	return mock
}

func (_m *MockClient) EXPECT() *_MockClientRecorder {
	return _m.recorder
}

func (_m *MockClient) API() types.Client {
	ret := _m.ctrl.Call(_m, "API")
	ret0, _ := ret[0].(types.Client)
	return ret0
}

func (_mr *_MockClientRecorder) API() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "API")
}

func (_m *MockClient) Integration() types0.IntegrationDriver {
	ret := _m.ctrl.Call(_m, "Integration")
	ret0, _ := ret[0].(types0.IntegrationDriver)
	return ret0
}

func (_mr *_MockClientRecorder) Integration() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Integration")
}

func (_m *MockClient) OS() types0.OSDriver {
	ret := _m.ctrl.Call(_m, "OS")
	ret0, _ := ret[0].(types0.OSDriver)
	return ret0
}

func (_mr *_MockClientRecorder) OS() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OS")
}

func (_m *MockClient) Storage() types0.StorageDriver {
	ret := _m.ctrl.Call(_m, "Storage")
	ret0, _ := ret[0].(types0.StorageDriver)
	return ret0
}

func (_mr *_MockClientRecorder) Storage() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Storage")
}
